[book]
authors = ["siu"]
language = "zh-CN"
multilingual = false
src = "src"
title = "笨方法学 Rust（Learn Rust the hard way）"


[output.html]
git-repository-url = "https://github.com/siu91/LearnRustTheHardWay"
edit-url-template = "https://github.com/siu91/LearnRustTheHardWay/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
