[book]
authors = ["siu"]
language = "en"
multilingual = false
src = "src"
title = "笨方法学 Rust（Learn Rust the hard way）"


[output.html]
git-repository-url = "https://github.com/siu91/LearnRustTheHardWay"
edit-url-template = "https://github.com/siu91/LearnRustTheHardWay/edit/main/{path}"
